version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_APP=server.py
    volumes:
      - ./backend/data:/app/backend/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"

  notebooks:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    command: >
      sh -c "pip install notebook &&
         jupyter notebook --notebook-dir=/app/notebooks --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"

    volumes:
      - ./notebooks:/app/notebooks
